#!/usr/bin/env python3
"""
エロゲ自動生成パイプライン
Google Gemini API (無料) を使ってシナリオ・台詞を生成し、Ren'Py プロジェクトを出力する
"""
import json
import re
import sys
from pathlib import Path
import google.generativeai as genai

# Windows CP932 対策
if sys.platform == "win32":
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

# ── 設定 ──────────────────────────────────────────
CONFIG_PATH = Path(__file__).parent / "config.json"
OUTPUT_DIR  = Path(__file__).parent / "output"
MODEL_NAME  = "gemini-2.0-flash"   # 無料枠あり

def init_client():
    api_key = None
    env_file = Path(__file__).parent / ".env"
    if env_file.exists():
        for line in env_file.read_text(encoding="utf-8").splitlines():
            if line.startswith("GEMINI_API_KEY="):
                api_key = line.split("=", 1)[1].strip()
    if not api_key:
        import os
        api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("ERROR: GEMINI_API_KEY が設定されていません。")
        print("  .env ファイルに GEMINI_API_KEY=your_key を書くか、")
        print("  環境変数 GEMINI_API_KEY を設定してください。")
        print("  無料キー取得: https://aistudio.google.com/")
        sys.exit(1)
    genai.configure(api_key=api_key)
    return genai.GenerativeModel(MODEL_NAME)

# ── ユーティリティ ──────────────────────────────────
def call_gemini(model, prompt: str, system: str = "") -> str:
    """Gemini API を呼び出してテキストを返す（ストリーミング表示）"""
    full_prompt = f"{system}\n\n{prompt}" if system else prompt
    result = []
    for chunk in model.generate_content(full_prompt, stream=True):
        text = chunk.text if chunk.text else ""
        print(text, end="", flush=True)
        result.append(text)
    print()
    return "".join(result)

def load_config() -> dict:
    with open(CONFIG_PATH, encoding="utf-8") as f:
        return json.load(f)

# ── Step 1: あらすじ生成 ────────────────────────────
def generate_story_outline(model, cfg: dict) -> str:
    print("\n=== [1/4] あらすじ生成中... ===\n")
    heroine_desc = "\n".join(
        f"- {h['name']}（{h['role']}）: {h['personality']}"
        for h in cfg["heroines"]
    )
    adult_note = (
        "成人向けの描写を含めてください。" if cfg.get("adult_content")
        else "全年齢向けの甘いロマンスを中心にしてください。"
    )
    prompt = f"""以下の設定でビジュアルノベルのあらすじを作成してください。

タイトル: {cfg['title']}
ジャンル: {cfg['genre']}
舞台: {cfg['setting']}
主人公: {cfg['protagonist']['description']}
ヒロイン:
{heroine_desc}
トーン: {cfg['tone']}
シーン数: {cfg['num_scenes']}

{adult_note}

出力形式:
- 全体のあらすじ（200字程度）
- 各シーンのタイトルと概要（シーン番号, タイトル, 概要 の形式）"""

    return call_gemini(model, prompt)

# ── Step 2: キャラクター定義生成 ────────────────────
def generate_character_defs(model, cfg: dict) -> str:
    print("\n=== [2/4] キャラクター定義生成中... ===\n")
    prompt = f"""以下のキャラクターに対して Ren'Py の define 文を生成してください。

主人公名: {cfg['protagonist']['name']}
ヒロイン:
{json.dumps(cfg['heroines'], ensure_ascii=False, indent=2)}

以下の形式で出力してください（コードブロックなし、Ren'Py スクリプトのみ）:

define [変数名] = Character("[表示名]", color="[カラーコード]")

ヒロインごとにそれぞれ自然な日本語名の変数名を使ってください。
ナレーター(narrator)も追加してください。"""

    return call_gemini(model, prompt)

# ── Step 3: 全シーンのスクリプト生成 ──────────────────
def generate_scenes(model, cfg: dict, outline: str, char_defs: str) -> list:
    print("\n=== [3/4] シーンスクリプト生成中... ===\n")
    system = f"""あなたはビジュアルノベルのシナリオライターです。
Ren'Py スクリプト形式で台詞・ト書きを書いてください。

ルール:
- ナレーション: narrator "テキスト"
- キャラ台詞: [変数名] "台詞"
- 背景: scene bg_[場所名] with dissolve
- キャラ表示: show [キャラ変数名] [表情] at [位置]
- コメント: # コメント
- label は scene_[番号]: 形式
- コードブロック記号（```）は絶対に使わない
- 自然で感情豊かな日本語で書く
{"成人向けの描写も含めてよい。" if cfg.get("adult_content") else "全年齢向け。"}

キャラクター定義（参考）:
{char_defs}"""

    scenes = []
    for i in range(1, cfg["num_scenes"] + 1):
        print(f"\n--- シーン {i}/{cfg['num_scenes']} ---\n")
        prompt = f"""以下のあらすじのシーン {i} の Ren'Py スクリプトを書いてください。

あらすじ:
{outline}

このシーンの台詞は最低10行以上書いてください。
label scene_{i}: から始めてください。"""

        scene_script = call_gemini(model, prompt, system=system)
        # コードブロック記号が混入した場合に除去
        scene_script = re.sub(r"```[a-z]*\n?", "", scene_script).strip()
        scenes.append(scene_script)
    return scenes

# ── Step 4: Ren'Py プロジェクト出力 ──────────────────
def write_renpy_project(cfg: dict, char_defs: str, scenes: list):
    print("\n=== [4/4] Ren'Py プロジェクト出力中... ===\n")
    game_dir = OUTPUT_DIR / cfg["title"]
    (game_dir / "game").mkdir(parents=True, exist_ok=True)

    # コードブロック記号を除去
    char_defs = re.sub(r"```[a-z]*\n?", "", char_defs).strip()

    script = f"""# {cfg['title']} - 自動生成スクリプト
# Generated by eroge_generator (Google Gemini)

{char_defs}

label start:
    scene bg_school with fade
    narrator "物語が始まる..."
    jump scene_1

"""
    for i, scene in enumerate(scenes, 1):
        script += f"\n{scene}\n"
        if i < len(scenes):
            script += f"\n    jump scene_{i + 1}\n"
        else:
            script += "\n    return\n"

    (game_dir / "game" / "script.rpy").write_text(script, encoding="utf-8")
    print("  -> game/script.rpy を書き込みました")

    options = f'define config.title = "{cfg["title"]}"\n'
    (game_dir / "game" / "options.rpy").write_text(options, encoding="utf-8")

    readme = f"""# {cfg['title']}

自動生成された Ren'Py ビジュアルノベルプロジェクトです。

## 実行方法
1. Ren'Py SDK をダウンロード: https://www.renpy.org/
2. このフォルダを Ren'Py ランチャーで開く
3. Launch Project をクリック

## 注意
- 背景・立ち絵画像は別途用意が必要です（game/images/ フォルダに配置）
- 画像ファイル名は script.rpy の scene/show 文に合わせてください
"""
    (game_dir / "README.md").write_text(readme, encoding="utf-8")
    print("  -> README.md を書き込みました")
    print(f"\n完成: {game_dir}")
    return game_dir

# ── メイン ────────────────────────────────────────
def main():
    model = init_client()
    cfg   = load_config()
    print(f"ゲーム生成開始: {cfg['title']}")
    print(f"  ジャンル: {cfg['genre']} / シーン数: {cfg['num_scenes']}")

    outline   = generate_story_outline(model, cfg)
    char_defs = generate_character_defs(model, cfg)
    scenes    = generate_scenes(model, cfg, outline, char_defs)
    project   = write_renpy_project(cfg, char_defs, scenes)

    print(f"\n完成! -> {project}")

if __name__ == "__main__":
    main()
